// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbBQilLSwLH-bpl3LWJ-RFlSSDATkNDD4',
    appId: '1:118045213566:web:5a9c79f0fe4bdcb85be92f',
    messagingSenderId: '118045213566',
    projectId: 'presence-e0b66',
    authDomain: 'presence-e0b66.firebaseapp.com',
    storageBucket: 'presence-e0b66.firebasestorage.app',
    measurementId: 'G-WLYPF74HKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5D_8fCD61yja6x0va530x-RztRpHMMeU',
    appId: '1:118045213566:android:1a686af5708419d45be92f',
    messagingSenderId: '118045213566',
    projectId: 'presence-e0b66',
    storageBucket: 'presence-e0b66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGK1H2pq8BS1_yd7qPDW9hRDw_7ya2t2U',
    appId: '1:118045213566:ios:b4dce9ed2a76037d5be92f',
    messagingSenderId: '118045213566',
    projectId: 'presence-e0b66',
    storageBucket: 'presence-e0b66.firebasestorage.app',
    iosBundleId: 'com.fazryproject.presence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGK1H2pq8BS1_yd7qPDW9hRDw_7ya2t2U',
    appId: '1:118045213566:ios:b4dce9ed2a76037d5be92f',
    messagingSenderId: '118045213566',
    projectId: 'presence-e0b66',
    storageBucket: 'presence-e0b66.firebasestorage.app',
    iosBundleId: 'com.fazryproject.presence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbBQilLSwLH-bpl3LWJ-RFlSSDATkNDD4',
    appId: '1:118045213566:web:b1a7997c5754e1bd5be92f',
    messagingSenderId: '118045213566',
    projectId: 'presence-e0b66',
    authDomain: 'presence-e0b66.firebaseapp.com',
    storageBucket: 'presence-e0b66.firebasestorage.app',
    measurementId: 'G-P027XNN8MX',
  );
}
